// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9b2GdZWeBknWrzJ06gaOpd4Ga11ZbXC8',
    appId: '1:965193620047:web:02d140dd831136180ee83a',
    messagingSenderId: '965193620047',
    projectId: 'bookswap-db3fd',
    authDomain: 'bookswap-db3fd.firebaseapp.com',
    storageBucket: 'bookswap-db3fd.firebasestorage.app',
    measurementId: 'G-H2DWCJSHNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ZNuXcojUPn-ap5JKqdrjI3zqOm1QdGs',
    appId: '1:965193620047:android:77342d736fc82f630ee83a',
    messagingSenderId: '965193620047',
    projectId: 'bookswap-db3fd',
    storageBucket: 'bookswap-db3fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlq-j1nvXfBcK9-5t_YiM_i4HJ8597pWU',
    appId: '1:965193620047:ios:1a2b8d96c48fe46b0ee83a',
    messagingSenderId: '965193620047',
    projectId: 'bookswap-db3fd',
    storageBucket: 'bookswap-db3fd.firebasestorage.app',
    iosBundleId: 'com.example.bookswap',
  );
}
